name: Publish to npm

on:
  release:
    types: [published]  # Trigger only when a draft is published

jobs:
  publish:
    if: github.actor == 'badabing2005'
    runs-on: ubuntu-latest
    name: Publish to npm

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./publish

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Set npm Registry URL
        run: npm config set registry https://registry.npmjs.org/

      - name: Set npm Auth Token
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish
